#!/usr/bin/env node
/** Assemble the Electron shell, server bundle, web build, and runtime dependencies. */
import { execSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const desktopRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(desktopRoot, "../..");
const outDir = path.join(desktopRoot, "build", "app");
const webDist = path.join(repoRoot, "apps", "web", "dist");

if (!existsSync(path.join(webDist, "index.html"))) {
  console.error("apps/web/dist is missing — run `pnpm --filter @marlen/web build` first.");
  process.exit(1);
}

function installedDependencies(filter) {
  const raw = execSync(`pnpm --filter ${filter} list --prod --depth 0 --json`, {
    cwd: repoRoot,
    encoding: "utf8",
  });
  const [project] = JSON.parse(raw);
  return Object.fromEntries(
    Object.entries(project?.dependencies ?? {}).map(([name, info]) => [name, info.version]),
  );
}

const serverDeps = installedDependencies("@marlen/server");
const desktopDeps = installedDependencies("@marlen/desktop");

const EXCLUDED = new Set(["@marlen/shared", "tsx"]);

const runtimeDeps = Object.fromEntries(
  [
    ...Object.entries(serverDeps).filter(([name]) => !EXCLUDED.has(name)),
    ["electron-updater", desktopDeps["electron-updater"]],
  ].sort(([a], [b]) => a.localeCompare(b)),
);

for (const stale of ["main.cjs", "preload.cjs", "server", "web", "resources", "package.json"]) {
  rmSync(path.join(outDir, stale), { recursive: true, force: true });
}
mkdirSync(outDir, { recursive: true });

const desktopPkg = JSON.parse(readFileSync(path.join(desktopRoot, "package.json"), "utf8"));
const appPkg = {
  name: "marlen",
  productName: "Marlen",
  version: desktopPkg.version,
  private: true,
  description: "Local-first AI email agent",
  author: "Marlen",
  main: "main.cjs",
  dependencies: runtimeDeps,
};
writeFileSync(path.join(outDir, "package.json"), `${JSON.stringify(appPkg, null, 2)}\n`);

await build({
  entryPoints: [
    path.join(desktopRoot, "src", "main.ts"),
    path.join(desktopRoot, "src", "preload.ts"),
  ],
  outdir: outDir,
  outExtension: { ".js": ".cjs" },
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  external: ["electron", "electron-updater"],
  logLevel: "warning",
});

await build({
  entryPoints: [path.join(repoRoot, "apps", "server", "src", "index.ts")],
  outfile: path.join(outDir, "server", "bundle.mjs"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  external: Object.keys(serverDeps).filter((name) => name !== "@marlen/shared"),
  logLevel: "warning",
});

cpSync(
  path.join(repoRoot, "apps", "server", "src", "agent", "prompts"),
  path.join(outDir, "server", "prompts"),
  { recursive: true },
);

cpSync(
  path.join(repoRoot, "apps", "server", "src", "services", "automations", "instructions"),
  path.join(outDir, "server", "instructions"),
  { recursive: true },
);

// Hide Electron markers before pdfjs loads so it stays on its Node path.
writeFileSync(
  path.join(outDir, "server", "index.mjs"),
  [
    "// Generated by scripts/build.mjs. See the server bundle build step.",
    "for (const patch of [",
    "  () => delete process.versions.electron,",
    "  () => delete process.type,",
    "]) {",
    "  try {",
    "    patch();",
    "  } catch {}",
    "}",
    'await import("./bundle.mjs");',
    "",
  ].join("\n"),
);

cpSync(webDist, path.join(outDir, "web"), { recursive: true });

// electron-builder does not copy installer resources into the app bundle.
mkdirSync(path.join(outDir, "resources"), { recursive: true });
cpSync(path.join(desktopRoot, "resources", "icon.png"), path.join(outDir, "resources", "icon.png"));

console.log(
  `assembled ${path.relative(repoRoot, outDir)} (v${appPkg.version}, ${Object.keys(runtimeDeps).length} runtime deps)`,
);
